### PR TITLE
setup.py: use package_data to include binary

### LINKED ISSUE #32: Python 3.8 install issue
I prefer to manage my Python packages with `pip`, so in the past I have installed PHCpy3 via:
```
cd PHC_src/src/Objects
make -f makefile_unix phcpy2c3.so
cd ../Python/PHCpy3
python3 -m pip install .
```
This worked with Python 3.6, but with Python 3.8 (and very recent versions of `pip`, `setuptools` and `wheel`), the above is no longer copying `phcpy2c3.so` into `site-packages/phcpy`.  Looking at the verbose output of `pip`, I see the garbled line:
```
copying phcpy/phcpy2c3.so -> build/bdist.linux-x86_64/wheel/sage/local/lib/python3.8/site-packages/phcpy
```
where site-packages is `/sage/local/lib/python3.8/site-packages/`.  I believe this has to do with the use of `get_python_lib` in `setup.py`.  

There is a simple fix which actually simplifies `setup.py`, I will create a pull-request for this shortly.

### PR DESCRIPTION
**Pull request by NathanDunfield**
Tested with both just `distutils` (i.e. `python3 setup.py install`) and `pip` (i.e. `python3 -m pip install `).  This would fix #32.

### CODE REVIEW

**Comment by janverschelde** [comment]
Thanks for these modifications.  The new setup.py works for python3, but for python2, the phcpy2c3.so in
  package_data = {'phcpy':['phcpy2c3.so']} 
should be changed into phcpy2c2.so.

**Comment by NathanDunfield** [comment]
Fixed now.  I should have tested Python 2 as well, sorry about that.

**Comment by janverschelde** [comment]
Thanks for this improvement.

**Comment by janverschelde** [comment]
Reopened after an accidental close and merged the pull request.

**Pull request merged**
